name: "Increment the version in a text file"
description: "increment the version in a text file"
inputs:
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  versionCode:
    description: "The new version code"
    required: false
  versionName:
    description: "The new version name"
    required: false
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node12"
  main: "index.js"
branding:
  color: 'blue'
  icon: 'anchor'